name: Checks
on:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Checkout persistent data
        uses: actions/checkout@v3
        with:
          ref: data
          fetch-depth: 0
          path: data
      - name: Setup environment
        run: |
          echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_REPO=${{ github.repository }}" >> $GITHUB_ENV
      - name: Run checks
        run: |
          python src/entry.py
      - name: Test
        run: |
          curl -i -u $GITHUB_ACTOR:$GITHUB_TOKEN https://api.github.com/repos/$GITHUB_REPO/issues
      - name: Commit persistent data
        run: |
          cd data
          if [ ! -z "$(git status --porcelain)" ]; then 
            git config --global credential.helper ""
            git config --global --add credential.helper store
            echo "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com" >> ~/.git-credentials
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git config user.name "${{ github.actor }}"
            git add -A
            git commit -m "Persistent data update"
            git push
          fi
